server:
  domain: user
  version: 1.0
  jwtSecret: TianSuo
  grpcAddress: 127.0.0.1:10001

mysql:
  diverName: mysql
  host: 172.24.201.56
  port: 3306
  database: grpc_todolist_tmp
  username: root
  password: root
  charset: utf8mb4

etcd:
  address: 127.0.0.1:2379

redis:
  address: 127.0.0.1:6379

